// app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";
import ClientProviders from "./ClientProviders"; // Import the client-side provider

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>My Next.js Shopify App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
